name: the_darkblade
description: "The Darkblade - A 2D Souls-like Action RPG built with Flutter & Flame."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-162.1.beta

dependencies:
  flutter:
    sdk: flutter

  # Game engine
  flame: ^1.30.1
  flame_audio: ^2.11.8
  flame_tiled: ^3.0.11

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/tiles/
